answer_app/urls.py
"""urls file for answer_app"""

from django.conf.urls import include, url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^success$', views.success, name='success'),
]

let_me_answer/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('answer_app.urls', namespace='answer_app'))
]

answer_app/models.py
from django.db import models
from django import forms

# Create your models here.
class Question(models.Model):
	"""A question which a user has submitted"""
	question = models.TextField(max_length = 1000,)
	user_email = models.CharField( max_length = 50)
	date_added = models.DateTimeField(auto_now_add=True)
	def __str__(self):
		"""Return a string representation of the model."""
		return self.text

let_me_answer_that/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

answer_app/forms.py
from django import forms
from django.forms import Textarea, TextInput

from .models import Question

class QuestionForm(forms.ModelForm):
	class Meta:
		model = Question
		fields = ['question','user_email']
		widgets = {
			'question':Textarea(attrs={'placeholder': 'Go ahead...Ask me anything.'}),
			'user_email':TextInput(attrs={'placeholder': 'Enter your email address.'}),
			}
		labels = {'question': '','user_email': ''}

answer_app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .forms import QuestionForm

# Create your views here.
def index(request):
	"""Display homepage"""
	if request.method != 'POST':
		# No data submitted. Create blank form
		form = QuestionForm()
	else:
		# POST data submitted; process data
		form = QuestionForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('answer_app:success'))
			
	context = {'form': form}
	return render(request, 'answer_app/index.html', context)
	
def success(request):
	"""Display question submitted page"""
	return render(request, 'answer_app/success.html')

answer_app/templates/answer_app/LetMeAnswerThat.html
<html>
	<head>
		<title> Let me answer that...</title>
		<link href= "style.css" type="text/css" rel="stylesheet" />
	</head>
		
	<body>
		<h1> Let me answer that for you!</h1>
		
		<p> 
			<form action="SubmissionReceipt.html">
			<h3> Step 1: Ask a question. </h3>
			<br />
			<input type="text" name="question" placeholder="Go ahead...Ask me anything." /> 
			<br />
			<h3>Step 2: Enter your email address. </h3>
			<br />
			<input type="email" name="emailAddress" placeholder="Enter your email address." />
			<br />
			<h3>Step 3: Hit submit to get an answer from REAL PEOPLE! </h3>
			<br />
			<input type="submit" name="submitButton" value="submit"  />  
			</form>
		</p>
		
	</body>

answer_app/templates/answer_app/SubmissionReceipt.html
<html>

	<head>
		<title> Question Submitted. </title>
		<link href= "style.css" type="text/css" rel="stylesheet" />
	</head>


	<body>
		<h1> You have successfully submitted your question. </h1>
	</body>

answer_app/templates/answer_app/base.html
<html>
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'answer_app/style.css' %}" />
{% block static-files %}{% endblock static-files %}

	<head>
		<title> {% block title %}{% endblock title %} </title>
		
	</head>
		
	<body>
		{% block content %}{% endblock content %}
	</body>
</html>

answer_app/templates/answer_app/index.html
{% extends "answer_app/base.html" %}

{% block static-files %}{% endblock static-files %}

{% block title %}Let me answer that...{% endblock title %}
		
{% block content %}
	<h1> Let me answer that for you!</h1>
		
		<p> 
			<form action="{% url 'answer_app:index' %}" method='POST'>
				{% csrf_token %}
				<p>test</p>
				{{ form.question }}
				<p>other test</p>
				{{ form.user_email}}						
			<input type="submit" name="submitButton" value="submit"  />  
		</p>
{% endblock content %}
	</form>	<h3> Step 1: Ask a question. </h3>
			<br />
			<input type="text" name="question" placeholder="Go ahead...Ask me anything." /> 
			<br />
			<h3>Step 2: Enter your email address. </h3>
			<br />
			<input type="email" name="emailAddress" placeholder="Enter your email address." />
			<br />
			<h3>Step 3: Hit submit to get an answer from REAL PEOPLE! </h3>
			<br />

answer_app/templates/answer_app/success.html
<html>

	<head>
		<title> Question Submitted. </title>
		<link href= "style.css" type="text/css" rel="stylesheet" />
	</head>


	<body>
		<h1> You have successfully submitted your question. </h1>
	</body>